#!/bin/bash

if (whoami == root)
then
    echo "This script assumes you have installed ghpb in /opt/ghpb-bin and that you run it as a service (see https://github.com/Nicemanss/hpb-tools/blob/master/hpb-install )"
    read -r -p "Are you sure you want to continue? [y/N] " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
    then
        if [ -d /opt/ghpb-bin ] && [ -f /etc/systemd/system/ghpb@.service ]
        then
            # Check the latest hpb-go release
            LATESTVERSION=`curl -s https://api.github.com/repos/hpb-project/go-hpb/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`
            echo "Stopping ghpb service"
            systemctl stop ghpb@root.service

            echo "Setting up temp directories"
            if [ -d /root/hpb-temp ]
            then
                rm -rf /root/hpb-temp
            fi

            mkdir /root/hpb-temp
            cd /root/hpb-temp

            echo "Downloading the latest release of HPB"
            wget https://github.com/hpb-project/go-hpb/archive/$LATESTVERSION.zip
            unzip $LATESTVERSION.zip
            cd go-hpb-$LATESTVERSION

            echo "Building release $LATESTVERSION"
            make all

            echo "Copying binaries"
            cp build/bin/* /opt/ghpb-bin

            echo "Backing up keystore data"
            mv /opt/ghpb-bin/node/data/keystore /opt/ghpb-bin

            echo "Clearing node data"
            rm -rf /opt/ghpb-bin/node

            echo "Initializing genesis block"
            cd /opt/ghpb-bin/
            wget https://raw.githubusercontent.com/hpb-project/hpb-release/master/config/gensis.json
            ./ghpb --datadir node/data init gensis.json

            echo "Restoring keystore data"
            mv /opt/ghpb-bin/keystore /opt/ghpb-bin/node/data/

            echo "Starting ghpb service"
            systemctl start ghpb@root.service
            echo "Node started. Run /opt/ghpb-bin/ghpb attach http://127.0.0.1:8545 to attach to console"

            echo "Cleaning temp directories"
            rm -rf /root/hpb-temp
        else
            echo "/opt/ghpb-bin or /etc/systemd/system/ghpb@.service does not exist, exiting."
        fi

    else
        echo "Exiting"
    fi
else
    echo "You must be root to run this"
fi
